### ISSUE TITLE
URL in description and README broken

### ISSUE THREAD

**Issue by githubteacher** [githubschool/github-games-idmarjr#2]
The URL in the repository description and the one in the README are pointing to githubschool's copy of the game instead of yours. 

 Please fix both so they point to your copy of the game at https://githubschool.github.io/github-games-idmarjr

**Comment by idmarjr** [comment]
Fix: https://github.com/githubschool/github-games-idmarjr/commit/935ec02bb41e684011b5113185d3152b772b9a11
